language: ruby
rvm:
  - "1.9.3"
# uncomment this line if your project needs to run something other than `rake`:
# script: bundle exec rspec spec

script:
  - bundle exec rake db:test:prepare
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rspec spec/

env: